[settings]
ruby.compile = false

[tools]
node = { version = "24", postinstall = "mise exec -- npm ci" }
ruby = { version = "3.3.9", postinstall = "mise exec -- bundle config set --local path 'vendor/bundle'; mise exec -- bundle install" }

[tasks.install-deps]
description = "Install project dependencies from lockfiles"
run = [
  "mise exec -- npm ci",
  # `postinstall` runs on tool install/update, but if tools come from cached/mounted volume, then the local bundle vendor may have not been configured.
  "mise exec -- bundle config set --local path 'vendor/bundle'",
  "mise exec -- bundle install"
]
