theme: jekyll-theme-minimal
title: "Christopher Bull, PhD"
logo: /img/Chris_Bull_2018_500px.jpg
description: "Personal web page of Dr Christopher Bull"
show_downloads: false
google_analytics: G-Z9C1WJKHNL