remote_theme: "mmistakes/minimal-mistakes@4.21.0"
locale: "en-GB"
title: "Christopher Bull"
subtitle: "Researcher of Digital Health and Software Engineering"
logo: /assets/images/Chris_Bull_2018_500px.webp
description: "Dr Christopher Bull is a Senior Researcher in Digital Health and Software Engineering."
show_downloads: false
google_analytics: G-Z9C1WJKHNL
plugins:
  - jekyll-include-cache