remote_theme: "mmistakes/minimal-mistakes@4.21.0"
locale: "en-GB"
name: "Christopher Bull"
title: "Christopher Bull"
subtitle: "Researcher of Digital Health and Software Engineering"
logo: /assets/images/Chris_Bull_2018_500px.webp
description: "Dr Christopher Bull is a Senior Researcher in Digital Health and Software Engineering."
show_downloads: false
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-Z9C1WJKHNL"
twitter:
  username: "VirtualChrisB"
social:
  type: Person
  name: "Christopher Bull"
  links:
    - "https://twitter.com/VirtualChrisB"
    - "https://www.linkedin.com/in/christophernbull"
plugins:
  - jekyll-include-cache