theme: jekyll-theme-minimal
title: "Christopher Bull"
logo: /img/Chris_Bull_2018_500px.webp
description: "Dr Christopher Bull is a Senior Researcher in Digital Health and Software Engineering."
show_downloads: false
google_analytics: G-Z9C1WJKHNL