remote_theme: "mmistakes/minimal-mistakes@4.22.0"
locale: "en-GB"
name: "Dr Christopher Bull"
title: "Christopher Bull"
subtitle: "Researcher of Digital Health and Software Engineering"
logo: /assets/images/Chris_Bull_2018_100px.webp
description: "Dr Christopher Bull is a Senior Researcher in Digital Health and Software Engineering."
show_downloads: false
author:
  name: "Dr Christopher Bull"
  avatar: "/assets/images/Chris_Bull_2018_500px.webp"
  # bio: "I am a researcher." # Note: Markdown is allowed
  location: "Lancaster, UK"
  links:
    - label: "Lancaster University"
      icon: "fas fa-fw fa-university"
      url: "https://www.lancaster.ac.uk/people-profiles/christopher-bull"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/christophernbull/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/VirtualChrisB"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ChristopherBull"
    - label: "ORCID"
      icon: "fab fa-fw fa-orcid"
      url: "https://orcid.org/0000-0002-9811-4190"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-link"
      url: "https://scholar.google.co.uk/citations?user=2c1JyAkAAAAJ"
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-Z9C1WJKHNL"
twitter:
  username: "VirtualChrisB"
social:
  type: Person
  name: "Dr Christopher Bull"
  links:
    - "https://twitter.com/VirtualChrisB"
    - "https://www.linkedin.com/in/christophernbull"
plugins:
  - jekyll-include-cache
atom_feed:
  # Hide atom_feed until blog/news items added and browseable
  hide: true
footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/christophernbull/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/VirtualChrisB"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ChristopherBull"
