name: Tests

on: [push, pull_request]

jobs:
  spelling:
    name: Spelling
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v6
      - name: Extract Node version from .mise.toml
        id: node_version
        run: echo "version=$(sed -n 's/^[[:space:]]*node[[:space:]]*=[[:space:]]*\"\(.*\)\"/\1/p' .mise.toml)" >> $GITHUB_OUTPUT
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ steps.node_version.outputs.version }}
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Check spelling
        run: npm run spell

  lint:
    name: Linting
    runs-on: ubuntu-slim
    # Wait for first job (for dep cache)
    needs: spelling
    steps:
      - uses: actions/checkout@v6
      - name: Extract Node version from .mise.toml
        id: node_version
        run: echo "version=$(sed -n 's/^[[:space:]]*node[[:space:]]*=[[:space:]]*\"\(.*\)\"/\1/p' .mise.toml)" >> $GITHUB_OUTPUT
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ steps.node_version.outputs.version }}
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Do linting
        run: npm run lint
